/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, it, expect, vi, beforeEach } from "vitest"
import { NextRequest } from "next/server"
import { GET as getExport } from "@/app/api/projects/[projectId]/export/route"

const mockActivityLogsStore: any[] = []

const mockUser = { id: "user_test_1", name: "Alice Lead", email: "alice@test.com" }

const mockProject = {
  id: "proj_phase12",
  name: "Phase 12 Enterprise App",
  language: "en",
  workspace: { organizationId: "org_phase12" }
}

const mockDeliverables = [
  {
    id: "deliv_1",
    projectId: "proj_phase12",
    type: "WEBSITE_SPEC",
    versions: [
      { versionNumber: 1, content: { title: "Portal Spec", hero: "Welcome to AI Enterprise" } }
    ]
  },
  {
    id: "deliv_2",
    projectId: "proj_phase12",
    type: "SYSTEM_SPEC",
    versions: [
      { versionNumber: 1, content: { modules: [{ key: "jobs", name: "Job Openings" }] } }
    ]
  }
]

const mockRecords = [
  { id: "rec_1", projectId: "proj_phase12", moduleKey: "jobs", data: { title: "Senior AI Engineer", department: "Engineering" } }
]

vi.mock("@/lib/db", () => ({
  db: {
    project: {
      findUnique: vi.fn(async ({ where }: any) => {
        if (where.id === "proj_phase12") return mockProject
        return null
      })
    },
    deliverable: {
      findFirst: vi.fn(async ({ where }: any) => {
        return mockDeliverables.find((d) => d.projectId === where.projectId && d.type === where.type) || null
      }),
      findMany: vi.fn(async ({ where }: any) => {
        return mockDeliverables.filter((d) => d.projectId === where.projectId)
      })
    },
    generatedRecord: {
      findMany: vi.fn(async ({ where }: any) => {
        return mockRecords.filter((r) => r.projectId === where.projectId && r.moduleKey === where.moduleKey)
      })
    },
    activityLog: {
      create: vi.fn(async ({ data }: any) => {
        const item = { id: `act_${Date.now()}`, ...data, createdAt: new Date() }
        mockActivityLogsStore.push(item)
        return item
      })
    }
  }
}))

vi.mock("@/lib/access", () => ({
  requireProjectAccess: vi.fn(async (projectId: string) => {
    if (projectId === "unauthorized") {
      const err = new Error("Access Denied")
      err.name = "AccessError"
      throw err
    }
    return {
      user: mockUser,
      project: mockProject
    }
  })
}))

describe("Phase 12 — Enterprise Export Center & Master Report Compiler", () => {
  beforeEach(() => {
    mockActivityLogsStore.length = 0
  })

  it("should export Master Report in JSON format (`GET /api/projects/.../export?format=json`)", async () => {
    const req = new NextRequest("http://localhost:3000/api/projects/proj_phase12/export?format=json&type=ALL")
    const res = await getExport(req, { params: { projectId: "proj_phase12" } })

    expect(res.status).toBe(200)
    expect(res.headers.get("Content-Type")).toBe("application/json")
    const body = await res.json()
    expect(body.projectName).toBe("Phase 12 Enterprise App")
    expect(body.WEBSITE_SPEC).toBeDefined()
    expect(mockActivityLogsStore.some((a) => a.action === "export_generated")).toBe(true)
  })

  it("should export Master Report in Markdown format (`GET /api/projects/.../export?format=md`)", async () => {
    const req = new NextRequest("http://localhost:3000/api/projects/proj_phase12/export?format=md&type=ALL")
    const res = await getExport(req, { params: { projectId: "proj_phase12" } })

    expect(res.status).toBe(200)
    expect(res.headers.get("Content-Type")).toContain("text/markdown")
    const text = await res.text()
    expect(text).toContain("# Phase 12 Enterprise App")
    expect(text).toContain("Generated by Intelly AI")
  })

  it("should export Master Report in HTML format (`GET /api/projects/.../export?format=html`)", async () => {
    const req = new NextRequest("http://localhost:3000/api/projects/proj_phase12/export?format=html&type=ALL")
    const res = await getExport(req, { params: { projectId: "proj_phase12" } })

    expect(res.status).toBe(200)
    expect(res.headers.get("Content-Type")).toContain("text/html")
    const html = await res.text()
    expect(html).toContain("<!DOCTYPE html>")
    expect(html).toContain("Phase 12 Enterprise App")
  })

  it("should export system runtime records in CSV format (`GET /api/projects/.../export?format=csv&module=jobs`)", async () => {
    const req = new NextRequest("http://localhost:3000/api/projects/proj_phase12/export?format=csv&module=jobs")
    const res = await getExport(req, { params: { projectId: "proj_phase12" } })

    expect(res.status).toBe(200)
    expect(res.headers.get("Content-Type")).toContain("text/csv")
    const csv = await res.text()
    expect(csv).toContain("title,department")
    expect(csv).toContain('"Senior AI Engineer","Engineering"')
  })

  it("should return 400 error for unsupported format", async () => {
    const req = new NextRequest("http://localhost:3000/api/projects/proj_phase12/export?format=unsupported")
    const res = await getExport(req, { params: { projectId: "proj_phase12" } })

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toBe("Unsupported format")
  })
})
